/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VaultFavoritesRouteImport } from './routes/vault.favorites'
import { Route as AdminUnexeRouteImport } from './routes/admin.unexe'
import { Route as AdminLetmeuploadRouteImport } from './routes/admin.letmeupload'

const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultFavoritesRoute = VaultFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => VaultRoute,
} as any)
const AdminUnexeRoute = AdminUnexeRouteImport.update({
  id: '/admin/unexe',
  path: '/admin/unexe',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLetmeuploadRoute = AdminLetmeuploadRouteImport.update({
  id: '/admin/letmeupload',
  path: '/admin/letmeupload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/vault': typeof VaultRouteWithChildren
  '/admin/letmeupload': typeof AdminLetmeuploadRoute
  '/admin/unexe': typeof AdminUnexeRoute
  '/vault/favorites': typeof VaultFavoritesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/vault': typeof VaultRouteWithChildren
  '/admin/letmeupload': typeof AdminLetmeuploadRoute
  '/admin/unexe': typeof AdminUnexeRoute
  '/vault/favorites': typeof VaultFavoritesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/vault': typeof VaultRouteWithChildren
  '/admin/letmeupload': typeof AdminLetmeuploadRoute
  '/admin/unexe': typeof AdminUnexeRoute
  '/vault/favorites': typeof VaultFavoritesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/vault'
    | '/admin/letmeupload'
    | '/admin/unexe'
    | '/vault/favorites'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/vault'
    | '/admin/letmeupload'
    | '/admin/unexe'
    | '/vault/favorites'
  id:
    | '__root__'
    | '/'
    | '/vault'
    | '/admin/letmeupload'
    | '/admin/unexe'
    | '/vault/favorites'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VaultRoute: typeof VaultRouteWithChildren
  AdminLetmeuploadRoute: typeof AdminLetmeuploadRoute
  AdminUnexeRoute: typeof AdminUnexeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault/favorites': {
      id: '/vault/favorites'
      path: '/favorites'
      fullPath: '/vault/favorites'
      preLoaderRoute: typeof VaultFavoritesRouteImport
      parentRoute: typeof VaultRoute
    }
    '/admin/unexe': {
      id: '/admin/unexe'
      path: '/admin/unexe'
      fullPath: '/admin/unexe'
      preLoaderRoute: typeof AdminUnexeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/letmeupload': {
      id: '/admin/letmeupload'
      path: '/admin/letmeupload'
      fullPath: '/admin/letmeupload'
      preLoaderRoute: typeof AdminLetmeuploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface VaultRouteChildren {
  VaultFavoritesRoute: typeof VaultFavoritesRoute
}

const VaultRouteChildren: VaultRouteChildren = {
  VaultFavoritesRoute: VaultFavoritesRoute,
}

const VaultRouteWithChildren = VaultRoute._addFileChildren(VaultRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VaultRoute: VaultRouteWithChildren,
  AdminLetmeuploadRoute: AdminLetmeuploadRoute,
  AdminUnexeRoute: AdminUnexeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
